# Generated by Tests/Pickle/Build-Features.ps1 from Mod/Patches/. Do not edit by hand:
# a cherrypick pass plus a rerun of that script rewrites this file in full.
#
# One scenario per corrected mod. A scenario whose source mod is not in the modlist fails
# on its first step, naming that mod: that is the run missing a mod, not a broken correction.
# Every assertion reads the def after all patches have run, which is the value this mod owns.
Feature: every corrected item carries its arbitrated tech level

  Scenario: Akeron - Decorations
    Then mod "AKN.Decorations" is loaded
    And mod "nelim.techlevelfixes" loads after "AKN.Decorations"
    And def "AKN_DecorativeCables" field "techLevel" is "Industrial"
    And def "AKN_LooseCablesA" field "techLevel" is "Industrial"
    And def "AKN_LooseCablesB" field "techLevel" is "Industrial"
    And def "AKN_NeatCables" field "techLevel" is "Industrial"
    And def "AKN_OverheadCables" field "techLevel" is "Industrial"

  Scenario: Alis Cooking Table
    Then mod "Ali.CookingTable" is loaded
    And mod "nelim.techlevelfixes" loads after "Ali.CookingTable"
    And def "CookingTable" field "techLevel" is "Industrial"

  Scenario: Alis Crafting Table
    Then mod "Ali.CraftingTable" is loaded
    And mod "nelim.techlevelfixes" loads after "Ali.CraftingTable"
    And def "CraftingTable" field "techLevel" is "Industrial"

  Scenario: AmateurLLs Toys
    Then mod "AmateurLLTechBox.AmatuerLLsToys.0001" is loaded
    And mod "nelim.techlevelfixes" loads after "AmateurLLTechBox.AmatuerLLsToys.0001"
    And def "Gun_SparrowNestATurret" field "techLevel" is "Industrial"
    And def "Gun_SparrowNestBTurret" field "techLevel" is "Industrial"
    And def "LL_Turret_SparrowsNestA" field "techLevel" is "Industrial"
    And def "LL_Turret_SparrowsNestB" field "techLevel" is "Industrial"

  Scenario: Animal Caps!
    Then mod "AR13S.AnimalCaps" is loaded
    And mod "nelim.techlevelfixes" loads after "AR13S.AnimalCaps"
    And def "AR_Cap_Bear" field "techLevel" is "Medieval"
    And def "AR_Cap_Cat_Spotted" field "techLevel" is "Medieval"
    And def "AR_Cap_Duck" field "techLevel" is "Medieval"
    And def "AR_Cap_Gorilla" field "techLevel" is "Medieval"
    And def "AR_Cap_Panda" field "techLevel" is "Medieval"
    And def "AR_Cap_Pug" field "techLevel" is "Medieval"
    And def "AR_Cap_Rabbit_White" field "techLevel" is "Medieval"
    And def "AR_Cap_Shiba" field "techLevel" is "Medieval"
    And def "AR_Cap_Wolf" field "techLevel" is "Medieval"

  Scenario: Zombieland
    Then mod "brrainz.zombieland" is loaded
    And mod "nelim.techlevelfixes" loads after "brrainz.zombieland"
    And def "Thumper" field "techLevel" is "Medieval"
    And def "ZombieSerumSimple" field "techLevel" is "Industrial"
    And def "ZombieShocker" field "techLevel" is "Industrial"

  Scenario: Animal Commander
    Then mod "cedaro.animalcommander" is loaded
    And mod "nelim.techlevelfixes" loads after "cedaro.animalcommander"
    And def "ASC_ManualLeader" field "techLevel" is "Neolithic"

  Scenario: Animal Diapers
    Then mod "Dipsy.Diapers" is loaded
    And mod "nelim.techlevelfixes" loads after "Dipsy.Diapers"
    And def "diaper" field "techLevel" is "Medieval"

  Scenario: Altered Carbon 2: ReSleeved
    Then mod "hlx.UltratechAlteredCarbon" is loaded
    And mod "nelim.techlevelfixes" loads after "hlx.UltratechAlteredCarbon"
    And def "AC_CastingRelay" field "techLevel" is "Ultra"
    And def "AC_Gun_AncientGraserTurret" field "techLevel" is "Ultra"
    And def "AC_Gun_Autorevolver" field "techLevel" is "Industrial"
    And def "AC_NanoStorageDrive" field "techLevel" is "Ultra"
    And def "AC_NeuralConnector" field "techLevel" is "Ultra"
    And def "AC_NeuralEditor" field "techLevel" is "Ultra"
    And def "AC_NeuralMatrix" field "techLevel" is "Ultra"
    And def "AC_SleeveCasket" field "techLevel" is "Ultra"
    And def "AC_SleeveGestator" field "techLevel" is "Ultra"
    And def "AC_StackCache" field "techLevel" is "Ultra"
    And def "AC_Turret_AncientGraserTurret" field "techLevel" is "Ultra"

  Scenario: Alpines Window Walls and Skylights
    Then mod "IronSniper.WindowsSkylights" is loaded
    And mod "nelim.techlevelfixes" loads after "IronSniper.WindowsSkylights"
    And def "Windows_FramedWindow" field "techLevel" is "Industrial"
    And def "Windows_ReinforcedWindow" field "techLevel" is "Industrial"
    And def "Windows_Skylight" field "techLevel" is "Industrial"

  Scenario: Additional Tools Mod
    Then mod "LadyElizabeth.AdditionalToolsMod" is loaded
    And mod "nelim.techlevelfixes" loads after "LadyElizabeth.AdditionalToolsMod"
    And def "Book_Generic" field "techLevel" is "Medieval"
    And def "Bucket_Generic" field "techLevel" is "Medieval"
    And def "Hammer_Generic" field "techLevel" is "Medieval"
    And def "Machette_Generic" field "techLevel" is "Medieval"
    And def "Pickaxe_Steel" field "techLevel" is "Medieval"
    And def "Pickaxe_Wood" field "techLevel" is "Neolithic"

  Scenario: Alpha Thrumbo Extension
    Then mod "leafzxg.AlphaThrumboExtension" is loaded
    And mod "nelim.techlevelfixes" loads after "leafzxg.AlphaThrumboExtension"
    And def "AlphaThrumboMilk" field "techLevel" is "Spacer"

  Scenario: Advanced Raiders
    Then mod "Mlie.AdvancedRaiders" is loaded
    And mod "nelim.techlevelfixes" loads after "Mlie.AdvancedRaiders"
    And def "Apparel_BlueScreenBelt" field "techLevel" is "Industrial"

  Scenario: Alcohol Rehab - Sobrix
    Then mod "moncho.AlcoholRehabSobrix" is loaded
    And mod "nelim.techlevelfixes" loads after "moncho.AlcoholRehabSobrix"
    And def "Sobrix" field "techLevel" is "Industrial"

  Scenario: Akeron - Caretaker Apparel
    Then mod "Newton.AKN.CaretakerApparel" is loaded
    And mod "nelim.techlevelfixes" loads after "Newton.AKN.CaretakerApparel"
    And def "AKN_CaretakerPlateHelmet" field "techLevel" is "Medieval"

  Scenario: Animal Sarcophagus
    Then mod "overpl.AnimalSarcophagus" is loaded
    And mod "nelim.techlevelfixes" loads after "overpl.AnimalSarcophagus"
    And def "Animal_Sarcophagus" field "techLevel" is "Neolithic"
    And def "Animal_Sarcophagus_Large" field "techLevel" is "Neolithic"

  Scenario: Ancient Junk Loot
    Then mod "Romyashi.AncientJunkLoot" is loaded
    And mod "nelim.techlevelfixes" loads after "Romyashi.AncientJunkLoot"
    And def "Romy_AncientMicrowave" field "techLevel" is "Industrial"
    And def "Romy_AncientOven" field "techLevel" is "Industrial"
    And def "Romy_AncientPowerCell" field "techLevel" is "Spacer"
    And def "Romy_AncientPowerCellBlock" field "techLevel" is "Industrial"
    And def "Romy_AncientStove" field "techLevel" is "Industrial"
    And def "Romy_RestoredAncientLamp" field "techLevel" is "Industrial"

  Scenario: Ancient Relics
    Then mod "Romyashi.AncientRelics" is loaded
    And mod "nelim.techlevelfixes" loads after "Romyashi.AncientRelics"
    And def "Romy_Artillery_AncientMortar" field "techLevel" is "Ultra"
    And def "Romy_Gun_AncientMiniTurret" field "techLevel" is "Ultra"
    And def "Romy_Oldsteel" field "techLevel" is "Ultra"
    And def "Romy_Turret_AncientMiniTurret" field "techLevel" is "Ultra"
    And def "Romy_Turret_AncientMortar" field "techLevel" is "Ultra"

  Scenario: Animal Repeller
    Then mod "rye.animalrepeller" is loaded
    And mod "nelim.techlevelfixes" loads after "rye.animalrepeller"
    And def "AnimalRepeller" field "techLevel" is "Industrial"

  Scenario: Alpha Books
    Then mod "sarg.alphabooks" is loaded
    And mod "nelim.techlevelfixes" loads after "sarg.alphabooks"
    And def "ABooks_AdventuringLogs" field "techLevel" is "Medieval"
    And def "ABooks_ArmyManual" field "techLevel" is "Industrial"
    And def "ABooks_BookOfPortents" field "techLevel" is "Archotech"
    And def "ABooks_BotanicalCompendium" field "techLevel" is "Industrial"
    And def "ABooks_BurnedBook" field "techLevel" is "Medieval"
    And def "ABooks_DurathreadTechniques" field "techLevel" is "Industrial"
    And def "ABooks_InstructionManual" field "techLevel" is "Industrial"
    And def "ABooks_LustySauridMaid" field "techLevel" is "Medieval"
    And def "ABooks_MedicalJournal" field "techLevel" is "Industrial"
    And def "ABooks_MidasTome" field "techLevel" is "Archotech"
    And def "ABooks_OfficeBinder" field "techLevel" is "Industrial"
    And def "ABooks_PoliticalPamphlet" field "techLevel" is "Medieval"
    And def "ABooks_PsychologyBook" field "techLevel" is "Industrial"
    And def "ABooks_RestaurantGuide" field "techLevel" is "Industrial"
    And def "ABooks_RuinedBook" field "techLevel" is "Medieval"
    And def "ABooks_SelfHelpBook" field "techLevel" is "Industrial"
    And def "ABooks_SurvivalGuide" field "techLevel" is "Neolithic"
    And def "ABooks_TheChickenBook" field "techLevel" is "Archotech"
    And def "ABooks_TomeOfFire" field "techLevel" is "Archotech"
    And def "ABooks_TrainingManual" field "techLevel" is "Medieval"
    And def "ABooks_TreatiseOfStainlessSteel" field "techLevel" is "Industrial"
    And def "ABooks_TynansBook" field "techLevel" is "Industrial"
    And def "ABooks_ZoologicalCompendium" field "techLevel" is "Industrial"

  Scenario: Advanced Brewery
    Then mod "starter.beeer" is loaded
    And mod "nelim.techlevelfixes" loads after "starter.beeer"
    And def "ElectricBrewery" field "techLevel" is "Industrial"
    And def "HiTechBrewery" field "techLevel" is "Spacer"

  Scenario: All That Glitters: Glitter-Craft
    Then mod "TurboPickle.GlitterCraft" is loaded
    And mod "nelim.techlevelfixes" loads after "TurboPickle.GlitterCraft"
    And def "GlitterCraft_BrawlerArmor" field "techLevel" is "Spacer"
    And def "GlitterCraft_BulwarkArmor" field "techLevel" is "Spacer"
    And def "GlitterCraft_ChargeCannon" field "techLevel" is "Spacer"
    And def "GlitterCraft_Electronics" field "techLevel" is "Spacer"
    And def "GlitterCraft_Frame" field "techLevel" is "Ultra"
    And def "GlitterCraft_GlitterSteel" field "techLevel" is "Spacer"
    And def "GlitterCraft_HyperVelocityBullpup" field "techLevel" is "Spacer"
    And def "GlitterCraft_HyperVelocityPistol" field "techLevel" is "Spacer"
    And def "GlitterCraft_HyperVelocityRifle" field "techLevel" is "Spacer"
    And def "GlitterCraft_Knife" field "techLevel" is "Spacer"
    And def "GlitterCraft_MiniaturizedReactor" field "techLevel" is "Spacer"
    And def "GlitterCraft_Plating" field "techLevel" is "Spacer"
    And def "GlitterCraft_ReconArmor" field "techLevel" is "Spacer"
    And def "GlitterCraft_ReconHelmet" field "techLevel" is "Spacer"
    And def "GlitterCraft_Saber" field "techLevel" is "Spacer"
    And def "GlitterCraft_SmartRifle" field "techLevel" is "Spacer"
    And def "GlitterCraft_TrooperArmor" field "techLevel" is "Spacer"
    And def "GlitterCraft_TrooperHelmet" field "techLevel" is "Spacer"

  Scenario: Animal Simple Command
    Then mod "Udon.AnimalSimpleCommand" is loaded
    And mod "nelim.techlevelfixes" loads after "Udon.AnimalSimpleCommand"
    And def "ASC_ManualDefend" field "techLevel" is "Neolithic"
    And def "ASC_ManualHide" field "techLevel" is "Neolithic"
    And def "ASC_ManualLeader" field "techLevel" is "Neolithic"
    And def "ASC_ManualProvoke" field "techLevel" is "Neolithic"

  Scenario: [RF]Body Type Extend
    Then mod "Vanya.Outsource.BodyTypeExtend" is loaded
    And mod "nelim.techlevelfixes" loads after "Vanya.Outsource.BodyTypeExtend"
    And def "PlasticDevice" field "techLevel" is "Industrial"
    And def "RicoFox_BathingSuit" field "techLevel" is "Industrial"
    And def "RicoFox_BunnyGirl" field "techLevel" is "Industrial"

  Scenario: Alchemy
    Then mod "zal.alchemy" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.alchemy"
    And def "AlchemyAlchemy" field "techLevel" is "Medieval"
    And def "AlchemyBench" field "techLevel" is "Medieval"

  Scenario: Alternative Power Solutions
    Then mod "zal.alternativepowersolutions" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.alternativepowersolutions"
    And def "APS_ConcentratedSolarPowerStation" field "techLevel" is "Industrial"
    And def "APS_EnhancedGeothermalSystem" field "techLevel" is "Industrial"
    And def "APS_OffshoreWindTurbine" field "techLevel" is "Industrial"

  Scenario: Ancient Amulets
    Then mod "zal.ancientamulets" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.ancientamulets"
    And def "AMU_AmuletBarkeep" field "techLevel" is "Neolithic"
    And def "AMU_AmuletBlacksmith" field "techLevel" is "Neolithic"
    And def "AMU_AmuletForeman" field "techLevel" is "Neolithic"
    And def "AMU_AmuletSilverTongue" field "techLevel" is "Neolithic"
    And def "AMU_AmuletSoundMind" field "techLevel" is "Neolithic"
    And def "AMU_MedalArchitect" field "techLevel" is "Neolithic"
    And def "AMU_MedalChef" field "techLevel" is "Neolithic"
    And def "AMU_MedalCouturier" field "techLevel" is "Neolithic"
    And def "AMU_MedalDoctor" field "techLevel" is "Neolithic"
    And def "AMU_MedalFarmer" field "techLevel" is "Neolithic"
    And def "AMU_MedalMarksman" field "techLevel" is "Neolithic"
    And def "AMU_MedalMason" field "techLevel" is "Neolithic"
    And def "AMU_MedalMiner" field "techLevel" is "Neolithic"
    And def "AMU_MedalPugilist" field "techLevel" is "Neolithic"
    And def "AMU_MedalResearcher" field "techLevel" is "Neolithic"
    And def "AMU_MedalSculptor" field "techLevel" is "Neolithic"
    And def "AMU_MedalSmith" field "techLevel" is "Neolithic"
    And def "AMU_MedalSurgeon" field "techLevel" is "Neolithic"
    And def "AMU_MedalTamer" field "techLevel" is "Neolithic"
    And def "AMU_RingArchitect" field "techLevel" is "Neolithic"
    And def "AMU_RingBasicGold" field "techLevel" is "Neolithic"
    And def "AMU_RingBasicSilver" field "techLevel" is "Neolithic"
    And def "AMU_RingChef" field "techLevel" is "Neolithic"
    And def "AMU_RingCouturier" field "techLevel" is "Neolithic"
    And def "AMU_RingCustodian" field "techLevel" is "Neolithic"
    And def "AMU_RingDoctor" field "techLevel" is "Neolithic"
    And def "AMU_RingFarmer" field "techLevel" is "Neolithic"
    And def "AMU_RingMarksman" field "techLevel" is "Neolithic"
    And def "AMU_RingMason" field "techLevel" is "Neolithic"
    And def "AMU_RingMiner" field "techLevel" is "Neolithic"
    And def "AMU_RingPugilist" field "techLevel" is "Neolithic"
    And def "AMU_RingResearcher" field "techLevel" is "Neolithic"
    And def "AMU_RingSculptor" field "techLevel" is "Neolithic"
    And def "AMU_RingSmith" field "techLevel" is "Neolithic"
    And def "AMU_RingSurgeon" field "techLevel" is "Neolithic"
    And def "AMU_RingTamer" field "techLevel" is "Neolithic"

  Scenario: Angel Arm Revolver
    Then mod "zal.angelarm" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.angelarm"
    And def "VashGlasses" field "techLevel" is "Medieval"

  Scenario: Crystal Bodyparts
    Then mod "zal.crystalbodyparts" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.crystalbodyparts"
    And def "AdvCrystalArm" field "techLevel" is "Archotech"
    And def "AdvCrystalEar" field "techLevel" is "Archotech"
    And def "AdvCrystalEye" field "techLevel" is "Archotech"
    And def "AdvCrystalJoy" field "techLevel" is "Archotech"
    And def "AdvCrystalLeg" field "techLevel" is "Archotech"
    And def "AdvCrystalPain" field "techLevel" is "Archotech"
    And def "CBPAdvCrystalSkin" field "techLevel" is "Archotech"

  Scenario: Ancient Eastern Armory
    Then mod "zal.easternarmory" is loaded
    And mod "nelim.techlevelfixes" loads after "zal.easternarmory"
    And def "Ancient_AshigaruArmor" field "techLevel" is "Medieval"
    And def "Ancient_Brigandine" field "techLevel" is "Medieval"
    And def "Ancient_LeatherBrigandine" field "techLevel" is "Medieval"
    And def "Ancient_SamuraiYoroi" field "techLevel" is "Medieval"

