<#
.SYNOPSIS
  Validates every generated patch file under Mod/Patches/ against the shape this mod's
  cherrypick tool is supposed to always produce, and against About.xml's declared loadAfter.

.DESCRIPTION
  This mod ships no assembly and defines no Def of its own: every file under Mod/Patches/
  is a <Patch> of PatchOperationConditional blocks that each set one def's <techLevel>,
  generated by the author's own cherrypick tool and never hand-edited (every file says so
  in its own header comment). "XML tests" for a mod like this one are not the shared
  Check-DefRefs.ps1 / Check-XmlFields.ps1 scripts elsewhere in this repository - those walk
  actual Def XML (<ThingDef>, <ResearchProjectDef>, ...), and this mod ships none. What can
  go wrong here is specific to the generated shape itself:

    - a file whose declared "Corrections : N" comment does not match its actual operation
      count, which would mean the generator's own bookkeeping drifted from its output;
    - a PatchOperationConditional whose match (replace) and nomatch (add) branches disagree
      on the value to set - the one bug shape that would make the outcome depend on whether
      the target mod already had a techLevel, which the mod's whole design promises never
      to matter;
    - a <techLevel> value that is not one of the seven the game defines;
    - the same defName corrected twice in one file;
    - a patch file whose source mod (its own filename, the source mod's packageId) is not
      declared in About.xml's <loadAfter>, or a <loadAfter> entry with no patch file - the
      two are supposed to be exactly the same 29 names, checked here instead of by eye.

  Pure XML parsing, no RimWorld installation or assembly reference needed.

.EXAMPLE
  pwsh -File Tests/Check-Patches.ps1
#>
param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$Brief
)

$ErrorActionPreference = 'Stop'

$patchesDir = Join-Path $RepoRoot 'Mod/Patches'
$aboutPath  = Join-Path $RepoRoot 'Mod/About/About.xml'

$ValidTechLevels = @(
    'Undefined', 'Animal', 'Neolithic', 'Medieval', 'Industrial', 'Spacer', 'Ultra', 'Archotech'
)

$problems = New-Object System.Collections.Generic.List[string]
$patchFiles = Get-ChildItem -Path $patchesDir -Filter '*.xml' | Sort-Object Name

if ($patchFiles.Count -eq 0) {
    throw "No patch files found under $patchesDir"
}

$patchDefNames = 0
$sourcesSeen = New-Object System.Collections.Generic.HashSet[string]

foreach ($file in $patchFiles) {
    $sourceName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    [void]$sourcesSeen.Add($sourceName)

    [xml]$xml = $null
    try {
        $xml = [xml](Get-Content -Raw -Path $file.FullName)
    } catch {
        $problems.Add("$($file.Name): not well-formed XML - $($_.Exception.Message)")
        continue
    }

    if ($xml.DocumentElement.Name -cne 'Patch') {
        $problems.Add("$($file.Name): root element is <$($xml.DocumentElement.Name)>, expected <Patch>")
        continue
    }

    # "Corrections : N" lives in the header comment, as the child immediately before <Patch>.
    $headerComment = $null
    foreach ($node in $xml.ChildNodes) {
        if ($node.NodeType -eq 'Comment') { $headerComment = $node.Value }
    }
    $declaredCount = $null
    if ($headerComment -match 'Corrections\s*:\s*(\d+)') {
        $declaredCount = [int]$Matches[1]
    } else {
        $problems.Add("$($file.Name): header comment has no 'Corrections : N' line to check against")
    }

    $operations = $xml.Patch.Operation
    if ($null -eq $operations) { $operations = @() }
    elseif ($operations -isnot [System.Array]) { $operations = @($operations) }

    if ($null -ne $declaredCount -and $operations.Count -ne $declaredCount) {
        $problems.Add("$($file.Name): header says Corrections : $declaredCount, found $($operations.Count) <Operation> elements")
    }

    $defNamesInFile = New-Object System.Collections.Generic.HashSet[string]

    foreach ($op in $operations) {
        $patchDefNames++

        # PowerShell's -match/-eq/-contains are case-INsensitive by default, which is exactly
        # wrong here: XPath element names are case-sensitive, and a lowercase "thingDef" against
        # the game's actual "<ThingDef>" elements matches nothing at all, silently. Every
        # comparison below therefore uses the -c (case-sensitive) form on purpose.
        $class = $op.Class
        if ($class -cne 'PatchOperationConditional') {
            $problems.Add("$($file.Name): top-level Operation has Class=`"$class`", expected PatchOperationConditional")
            continue
        }

        # The def-type tag itself (ThingDef, thingDef, ResearchProjectDef, ...) is deliberately
        # NOT restricted to a fixed casing here. RimWorld's own def loader resolves a Def type
        # case-insensitively - confirmed against the installed Alchemy (Continued) source, which
        # declares "AlchemyBench" under a lowercase <thingDef> and loads it as a normal ThingDef
        # regardless. A patch's xpath still has to match the literal casing of the SOURCE FILE,
        # because XPath itself (unlike the def loader) is case-sensitive at the DOM level - so the
        # right invariant is not "always ThingDef", it is "every xpath referencing the same def in
        # the same operation uses the same casing", checked below via exact string equality against
        # the captured $outerXpath, not by re-deriving it from a fixed list.
        $outerXpath = $op.xpath
        if ($outerXpath -notmatch '^/Defs/([A-Za-z]+)\[defName="([^"]+)"\]$') {
            $problems.Add("$($file.Name): outer xpath `"$outerXpath`" does not match /Defs/<DefType>[defName=`"...`"]")
            continue
        }
        $defName = $Matches[2]

        if (-not $defNamesInFile.Add($defName)) {
            $problems.Add("$($file.Name): defName `"$defName`" is corrected more than once in this file")
        }

        if ($op.success -cne 'Always') {
            $problems.Add("$($file.Name)/$defName`: <success> is `"$($op.success)`", expected Always")
        }

        $inner = $op.match
        if ($null -eq $inner -or $inner.Class -cne 'PatchOperationConditional') {
            $problems.Add("$($file.Name)/$defName`: <match> is not a nested PatchOperationConditional")
            continue
        }
        $expectedInnerXpath = "$outerXpath/techLevel"
        if ($inner.xpath -cne $expectedInnerXpath) {
            $problems.Add("$($file.Name)/$defName`: inner xpath `"$($inner.xpath)`", expected `"$expectedInnerXpath`"")
        }

        $replace = $inner.match
        $add = $inner.nomatch

        if ($null -eq $replace -or $replace.Class -cne 'PatchOperationReplace') {
            $problems.Add("$($file.Name)/$defName`: <match><match> is not PatchOperationReplace")
        }
        if ($null -eq $add -or $add.Class -cne 'PatchOperationAdd') {
            $problems.Add("$($file.Name)/$defName`: <match><nomatch> is not PatchOperationAdd")
        }

        if ($null -ne $replace -and $replace.xpath -cne $expectedInnerXpath) {
            $problems.Add("$($file.Name)/$defName`: replace xpath `"$($replace.xpath)`", expected `"$expectedInnerXpath`"")
        }
        if ($null -ne $add -and $add.xpath -cne $outerXpath) {
            $problems.Add("$($file.Name)/$defName`: add xpath `"$($add.xpath)`", expected `"$outerXpath`"")
        }

        $replaceValue = $null
        $addValue = $null
        if ($null -ne $replace) { $replaceValue = $replace.value.techLevel }
        if ($null -ne $add)     { $addValue     = $add.value.techLevel }

        if ($null -eq $replaceValue -or $null -eq $addValue) {
            $problems.Add("$($file.Name)/$defName`: could not read a <value><techLevel> from one or both branches")
        } elseif ($replaceValue -cne $addValue) {
            $problems.Add("$($file.Name)/$defName`: replace branch sets techLevel=$replaceValue but add branch sets techLevel=$addValue")
        } elseif ($ValidTechLevels -cnotcontains $replaceValue) {
            $problems.Add("$($file.Name)/$defName`: techLevel `"$replaceValue`" is not one of: $($ValidTechLevels -join ', ')")
        }
    }
}

# Cross-check patch files against About.xml's <loadAfter>.
[xml]$about = Get-Content -Raw -Path $aboutPath
$loadAfter = New-Object System.Collections.Generic.HashSet[string]
foreach ($li in $about.ModMetaData.loadAfter.li) { [void]$loadAfter.Add([string]$li) }

foreach ($source in $sourcesSeen) {
    if (-not $loadAfter.Contains($source)) {
        $problems.Add("Mod/Patches/$source.xml has no matching <loadAfter><li>$source</li></loadAfter> entry in About.xml")
    }
}
foreach ($entry in $loadAfter) {
    if (-not $sourcesSeen.Contains($entry)) {
        $problems.Add("About.xml declares loadAfter `"$entry`" with no matching Mod/Patches/$entry.xml file")
    }
}

Write-Host "Checked $($patchFiles.Count) patch files, $patchDefNames corrections, $($loadAfter.Count) loadAfter entries."

if ($problems.Count -gt 0) {
    Write-Host ''
    Write-Host "$($problems.Count) problem(s):" -ForegroundColor Red
    foreach ($p in $problems) { Write-Host "  - $p" -ForegroundColor Red }
    exit 1
}

Write-Host 'PASS: every patch file matches the expected shape, and Mod/Patches/ matches loadAfter exactly.' -ForegroundColor Green
exit 0
