Feature: Generated tech-level patches
  Nelim's Tech Level Fixes ships no code of its own, only XML patches generated by the
  cherrypick tool, one file per source mod, each rewriting one or more items' <techLevel>.
  These scenarios describe the invariants that generated shape must hold for the mod's own
  promises in README.md to be true: a correction never depends on whether its target already
  had a techLevel, a missing target is harmless, and nothing but techLevel is ever touched.

  Scenarios here are executed by Tests/Run-Gherkin.ps1 against the real Mod/Patches/ tree and
  Mod/About/About.xml - not against a running game. In-game behaviour (raid loot, research
  gating, save/load) is out of this file's scope; see TESTING.md for those scenarios, which
  need RimWorld running and have not been executed.

  Scenario: A correction sets the same tech level however the target def already looked
    Given a generated correction for one defName
    When the target def already declared a techLevel, so the replace branch fires
    And the target def declared none, so the add branch fires instead
    Then both branches write the exact same techLevel value
    So that the outcome never depends on which branch actually ran

  Scenario: A correction only ever names one of the game's own tech levels
    Given a generated correction's techLevel value
    Then it is one of Undefined, Animal, Neolithic, Medieval, Industrial, Spacer, Ultra or Archotech
    So that no correction can silently write a value the game does not understand

  Scenario: A defName is corrected at most once per source mod
    Given all the corrections generated for one source mod
    Then no defName appears in more than one correction
    So that two corrections can never disagree about the same item

  Scenario: A missing source mod's correction is harmless by construction
    Given a generated correction's outer conditional
    Then its success is always reported as Always
    So that a target def that is not installed never raises a patch error,
     matching README.md's promise that "a correction whose item is missing does nothing"

  Scenario: Nothing but techLevel is ever written
    Given every value element any correction in the mod writes
    Then it always contains exactly one techLevel child and nothing else
    So that this mod can never silently change a label, a cost or any other field

  Scenario: Every corrected mod is declared, and only once
    Given the source mod named by each generated patch file
    And the mods declared in About.xml's loadAfter list
    Then the two sets are exactly the same, with no file missing a declaration
     and no declaration missing its file
    So that every correction truly runs after the mod it corrects, as the mod's own
     description promises
