<#
.SYNOPSIS
  Generates the Pickle feature files from Mod/Patches/, so they follow cherrypick.

.DESCRIPTION
  Every correction this mod makes is one assertion in game: the def, after all patches have run,
  carries the arbitrated techLevel. Pickle reads that with a built-in step,
  `def "X" field "techLevel" is "Y"`, so this mod needs no step assembly of its own - the feature
  files are the whole suite.

  Writing those 166 assertions by hand would rot the moment cherrypick adds a mod, the way the
  Zombieland addition of 2026-09-17 moved every count in this repository. So they are generated
  from the patch files themselves and committed; rerun this after any cherrypick pass.

  One scenario per source mod, and each opens with `Then mod "<packageId>" is loaded`. That line
  is the point: when a source mod is not in the modlist, the scenario fails there, naming it,
  instead of failing further down on a def that was never going to exist. A red scenario then
  reads as "this mod was not enabled for the run", which is information about the run, not a
  defect in the corrections.

.EXAMPLE
  .\Tests\Pickle\Build-Features.ps1
#>
param(
    [string]$RepoRoot = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$ErrorActionPreference = 'Stop'

$patchesDir  = Join-Path $RepoRoot 'Mod/Patches'
$featuresDir = Join-Path $PSScriptRoot 'Mod/Pickle/Features'
New-Item -ItemType Directory -Force -Path $featuresDir | Out-Null

$files = Get-ChildItem -Path $patchesDir -Filter '*.xml' | Sort-Object Name
if ($files.Count -eq 0) { throw "No patch files under $patchesDir" }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Generated by Tests/Pickle/Build-Features.ps1 from Mod/Patches/. Do not edit by hand:')
$lines.Add('# a cherrypick pass plus a rerun of that script rewrites this file in full.')
$lines.Add('#')
$lines.Add('# One scenario per corrected mod. A scenario whose source mod is not in the modlist fails')
$lines.Add('# on its first step, naming that mod: that is the run missing a mod, not a broken correction.')
$lines.Add('# Every assertion reads the def after all patches have run, which is the value this mod owns.')
$lines.Add('Feature: every corrected item carries its arbitrated tech level')
$lines.Add('')

$totalCorrections = 0
foreach ($file in $files) {
    $source = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    [xml]$xml = Get-Content -Raw -Path $file.FullName

    # The generated header names the upstream mod; fall back to the packageId when absent.
    $label = $source
    foreach ($node in $xml.ChildNodes) {
        if ($node.NodeType -eq 'Comment' -and $node.Value -match 'Source\s*:\s*(.+?)\s*\(') {
            $label = $Matches[1].Trim()
        }
    }

    $ops = $xml.Patch.Operation
    if ($null -eq $ops) { $ops = @() } elseif ($ops -isnot [System.Array]) { $ops = @($ops) }

    $lines.Add("  Scenario: $label")
    $lines.Add("    Then mod `"$source`" is loaded")
    $lines.Add("    And mod `"nelim.techlevelfixes`" loads after `"$source`"")
    foreach ($op in $ops) {
        if ($op.xpath -notmatch '\[defName="([^"]+)"\]$') {
            throw "$($file.Name): unexpected outer xpath '$($op.xpath)'"
        }
        $defName = $Matches[1]
        $value = $op.match.match.value.techLevel
        if ([string]::IsNullOrWhiteSpace($value)) { throw "$($file.Name)/$defName has no techLevel value" }
        $lines.Add("    And def `"$defName`" field `"techLevel`" is `"$value`"")
        $totalCorrections++
    }
    $lines.Add('')
}

$outPath = Join-Path $featuresDir '02-corrections.feature'
# UTF-8 without a BOM: Set-Content -Encoding UTF8 writes one on Windows PowerShell 5.1, and a BOM
# ahead of "# Generated by" is a stray glyph in the first comment of a Gherkin file.
[System.IO.File]::WriteAllText($outPath, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding $false))

Write-Host "Wrote $outPath"
Write-Host "$($files.Count) source mods, $totalCorrections corrections asserted."
